server:
  port: 8765
spring:
  application:
    name: discoveryservice
  profiles:
    active:
      default
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
