server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        git:
          uri: https://github.com/mgjoneskc/config.git
          search-paths: dailyplannerservice,discoveryservice
          username: mgjoneskc
          password: dexter613
